// src/app/(marketing)/terms/page.tsx
import Link from 'next/link'

import { Container } from '@/components/ui/container'
import { Divider } from '@/components/ui/divider'
import { Prose } from '@/components/ui/prose'
import { Section } from '@/components/ui/section'

import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description:
    'Terms and conditions for using Debate Lab, including acceptable use policies and legal agreements.',
  openGraph: {
    title: 'Terms of Service | Debate Lab',
    description: 'Terms and conditions for using Debate Lab.',
  },
}

const LAST_UPDATED = 'November 28, 2025'
const EFFECTIVE_DATE = 'November 28, 2025'

export default function TermsPage() {
  return (
    <>
      <Section>
        <Container>
          <header className="pt-8 md:pt-12 mb-12 max-w-3xl mx-auto text-center">
            <h1 className="text-4xl font-bold tracking-tight text-foreground sm:text-5xl">
              Terms of Service
            </h1>
            <p className="mt-4 text-muted-foreground">
              Last updated: {LAST_UPDATED} | Effective: {EFFECTIVE_DATE}
            </p>
          </header>

          <div className="max-w-3xl mx-auto">
            <article>
              <section id="introduction" className="scroll-mt-24">
                <h2 className="text-2xl font-bold tracking-tight text-foreground mb-4">
                  Introduction
                </h2>
                <Prose>
                  <p>
                    Welcome to Debate Lab. These Terms of Service (&quot;Terms&quot;) govern your
                    access to and use of the Debate Lab website and services (collectively, the
                    &quot;Service&quot;). By accessing or using the Service, you agree to be bound
                    by these Terms.
                  </p>
                  <p>
                    Please read these Terms carefully before using Debate Lab. If you do not agree
                    to these Terms, you may not access or use the Service.
                  </p>
                  <p>
                    Debate Lab is a platform that facilitates AI-powered debates between large
                    language models on topics you choose, with AI moderation and judging. The
                    Service is provided for entertainment and educational purposes.
                  </p>
                </Prose>
              </section>

              <Divider className="my-12" />

              <section id="definitions" className="scroll-mt-24">
                <h2 className="text-2xl font-bold tracking-tight text-foreground mb-4">
                  Definitions
                </h2>
                <Prose>
                  <ul>
                    <li>
                      <strong>&quot;Service&quot;</strong> refers to the Debate Lab website,
                      application, and all related services.
                    </li>
                    <li>
                      <strong>&quot;User,&quot; &quot;you,&quot; or &quot;your&quot;</strong> refers
                      to the individual accessing or using the Service.
                    </li>
                    <li>
                      <strong>&quot;We,&quot; &quot;us,&quot; or &quot;our&quot;</strong> refers to
                      Debate Lab and its operators.
                    </li>
                    <li>
                      <strong>&quot;Content&quot;</strong> refers to text, data, information, and
                      other materials submitted to or generated by the Service.
                    </li>
                    <li>
                      <strong>&quot;Debate&quot;</strong> refers to an AI-generated discussion
                      between language models on a specified topic.
                    </li>
                    <li>
                      <strong>&quot;AI Models&quot;</strong> refers to the third-party large
                      language models used to generate debate content.
                    </li>
                  </ul>
                </Prose>
              </section>

              <Divider className="my-12" />

              <section id="account-access" className="scroll-mt-24">
                <h2 className="text-2xl font-bold tracking-tight text-foreground mb-4">
                  Account & Access
                </h2>
                <Prose>
                  <p>
                    Debate Lab currently does not require account registration. Access is provided
                    through session-based identification. By using the Service, you agree to:
                  </p>
                  <ul>
                    <li>Use the Service only for lawful purposes</li>
                    <li>Not attempt to bypass any access restrictions or rate limits</li>
                    <li>Not impersonate others or misrepresent your identity</li>
                    <li>Not use automated systems to access the Service without permission</li>
                    <li>Maintain the security of any session identifiers</li>
                  </ul>
                  <p>
                    We reserve the right to restrict or terminate access to any user who violates
                    these Terms or uses the Service in a manner we deem harmful.
                  </p>
                </Prose>
              </section>

              <Divider className="my-12" />

              <section id="acceptable-use" className="scroll-mt-24">
                <h2 className="text-2xl font-bold tracking-tight text-foreground mb-4">
                  Acceptable Use
                </h2>
                <Prose>
                  <p>
                    You agree to use Debate Lab responsibly and ethically. The following uses are
                    strictly prohibited:
                  </p>

                  <h3>Prohibited Content</h3>
                  <ul>
                    <li>Content that promotes violence, hatred, or discrimination</li>
                    <li>Illegal content or content that facilitates illegal activities</li>
                    <li>Sexually explicit or pornographic content</li>
                    <li>Content that harasses, threatens, or bullies others</li>
                    <li>Misinformation intended to deceive or cause harm</li>
                    <li>Content that infringes on intellectual property rights</li>
                    <li>Malicious content including malware or phishing attempts</li>
                  </ul>

                  <h3>Prohibited Activities</h3>
                  <ul>
                    <li>Attempting to manipulate or &quot;jailbreak&quot; AI models</li>
                    <li>Circumventing content filters or safety measures</li>
                    <li>Scraping, mining, or extracting data from the Service</li>
                    <li>Reverse engineering or decompiling any part of the Service</li>
                    <li>Interfering with or disrupting the Service infrastructure</li>
                    <li>Using the Service to generate spam or bulk content</li>
                    <li>Reselling or commercially exploiting the Service without permission</li>
                  </ul>
                </Prose>
              </section>

              <Divider className="my-12" />

              <section id="debate-content" className="scroll-mt-24">
                <h2 className="text-2xl font-bold tracking-tight text-foreground mb-4">
                  Debate Content
                </h2>
                <Prose>
                  <p>When you submit a debate topic to Debate Lab:</p>
                  <ul>
                    <li>You are responsible for ensuring the topic is appropriate and lawful</li>
                    <li>Topics are subject to automated content filtering</li>
                    <li>We may reject or modify topics that violate our policies</li>
                    <li>Custom rules you provide must comply with acceptable use policies</li>
                  </ul>
                  <p>
                    Debate Lab is designed for constructive discourse. We encourage topics that are
                    thought-provoking, educational, or entertaining, while discouraging topics
                    designed to generate harmful or offensive content.
                  </p>
                </Prose>
              </section>

              <Divider className="my-12" />

              <section id="ai-generated-content" className="scroll-mt-24">
                <h2 className="text-2xl font-bold tracking-tight text-foreground mb-4">
                  AI-Generated Content
                </h2>
                <Prose>
                  <p>
                    All debate content is generated by artificial intelligence. You acknowledge and
                    agree that:
                  </p>
                  <ul>
                    <li>
                      <strong>No guarantee of accuracy</strong> — AI-generated content may contain
                      errors, inaccuracies, or fabricated information
                    </li>
                    <li>
                      <strong>Not professional advice</strong> — Content should not be relied upon
                      as legal, medical, financial, or other professional advice
                    </li>
                    <li>
                      <strong>Not our views</strong> — Arguments presented by AI models do not
                      represent the views or opinions of Debate Lab
                    </li>
                    <li>
                      <strong>May be biased</strong> — AI models may exhibit biases present in their
                      training data
                    </li>
                    <li>
                      <strong>Subject to change</strong> — The same topic may produce different
                      results on different occasions
                    </li>
                  </ul>
                  <p>
                    You are solely responsible for how you use or rely on AI-generated content from
                    Debate Lab.
                  </p>
                </Prose>
              </section>

              <Divider className="my-12" />

              <section id="intellectual-property" className="scroll-mt-24">
                <h2 className="text-2xl font-bold tracking-tight text-foreground mb-4">
                  Intellectual Property
                </h2>
                <Prose>
                  <h3>Our Intellectual Property</h3>
                  <p>
                    The Service, including its design, features, and original content, is owned by
                    Debate Lab and protected by copyright, trademark, and other intellectual
                    property laws. You may not copy, modify, distribute, or create derivative works
                    without our explicit permission.
                  </p>

                  <h3>AI-Generated Content Ownership</h3>
                  <p>
                    The intellectual property status of AI-generated content is evolving. For
                    debates generated through Debate Lab, you may use the output for personal,
                    non-commercial purposes. Commercial use requires explicit permission.
                  </p>
                </Prose>
              </section>

              <Divider className="my-12" />

              <section id="user-content" className="scroll-mt-24">
                <h2 className="text-2xl font-bold tracking-tight text-foreground mb-4">
                  User Content
                </h2>
                <Prose>
                  <p>
                    When you submit content to Debate Lab (such as debate topics or custom rules):
                  </p>
                  <ul>
                    <li>You retain ownership of the content you submit</li>
                    <li>
                      You grant us a license to use, process, and transmit your content as necessary
                      to provide the Service
                    </li>
                    <li>
                      You represent that you have the right to submit the content and that it does
                      not infringe on others&apos; rights
                    </li>
                    <li>You are responsible for any content you submit and its consequences</li>
                  </ul>
                </Prose>
              </section>

              <Divider className="my-12" />

              <section id="third-party-services" className="scroll-mt-24">
                <h2 className="text-2xl font-bold tracking-tight text-foreground mb-4">
                  Third-Party Services
                </h2>
                <Prose>
                  <p>Debate Lab relies on third-party services to function, including:</p>
                  <ul>
                    <li>OpenAI (GPT models)</li>
                    <li>Anthropic (Claude models)</li>
                    <li>xAI (Grok models)</li>
                    <li>Cloud hosting and infrastructure providers</li>
                  </ul>
                  <p>
                    Your use of the Service is also subject to the terms and policies of these
                    third-party providers. We are not responsible for the availability, accuracy, or
                    conduct of third-party services.
                  </p>
                </Prose>
              </section>

              <Divider className="my-12" />

              <section id="disclaimers" className="scroll-mt-24">
                <h2 className="text-2xl font-bold tracking-tight text-foreground mb-4">
                  Disclaimers
                </h2>
                <Prose>
                  <p>
                    THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT
                    WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED.
                  </p>
                  <p>We specifically disclaim:</p>
                  <ul>
                    <li>Warranties of merchantability and fitness for a particular purpose</li>
                    <li>Warranties that the Service will be uninterrupted or error-free</li>
                    <li>
                      Warranties regarding the accuracy or reliability of AI-generated content
                    </li>
                    <li>Warranties that the Service will meet your specific requirements</li>
                    <li>Warranties regarding the security of data transmission</li>
                  </ul>
                </Prose>
              </section>

              <Divider className="my-12" />

              <section id="limitation-of-liability" className="scroll-mt-24">
                <h2 className="text-2xl font-bold tracking-tight text-foreground mb-4">
                  Limitation of Liability
                </h2>
                <Prose>
                  <p>
                    TO THE MAXIMUM EXTENT PERMITTED BY LAW, DEBATE LAB SHALL NOT BE LIABLE FOR ANY
                    INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES.
                  </p>
                  <p>
                    This includes, but is not limited to, damages for loss of profits, data,
                    goodwill, or other intangible losses resulting from your use or inability to use
                    the Service, even if we have been advised of the possibility of such damages.
                  </p>
                  <p>
                    Our total liability for any claims arising from these Terms or the Service shall
                    not exceed the amount you paid us, if any, in the twelve months preceding the
                    claim.
                  </p>
                </Prose>
              </section>

              <Divider className="my-12" />

              <section id="indemnification" className="scroll-mt-24">
                <h2 className="text-2xl font-bold tracking-tight text-foreground mb-4">
                  Indemnification
                </h2>
                <Prose>
                  <p>
                    You agree to indemnify, defend, and hold harmless Debate Lab and its operators,
                    employees, and affiliates from any claims, damages, losses, liabilities, and
                    expenses (including legal fees) arising from:
                  </p>
                  <ul>
                    <li>Your use of the Service</li>
                    <li>Your violation of these Terms</li>
                    <li>Your violation of any rights of another party</li>
                    <li>Content you submit to the Service</li>
                  </ul>
                </Prose>
              </section>

              <Divider className="my-12" />

              <section id="termination" className="scroll-mt-24">
                <h2 className="text-2xl font-bold tracking-tight text-foreground mb-4">
                  Termination
                </h2>
                <Prose>
                  <p>
                    We may terminate or suspend your access to the Service immediately, without
                    prior notice, for any reason, including:
                  </p>
                  <ul>
                    <li>Violation of these Terms</li>
                    <li>Conduct that we believe is harmful to other users or the Service</li>
                    <li>Request by law enforcement or government agencies</li>
                    <li>Discontinuation or modification of the Service</li>
                  </ul>
                  <p>
                    Upon termination, your right to use the Service will immediately cease.
                    Provisions of these Terms that by their nature should survive termination shall
                    survive, including ownership, disclaimers, indemnification, and limitations of
                    liability.
                  </p>
                </Prose>
              </section>

              <Divider className="my-12" />

              <section id="governing-law" className="scroll-mt-24">
                <h2 className="text-2xl font-bold tracking-tight text-foreground mb-4">
                  Governing Law
                </h2>
                <Prose>
                  <p>
                    These Terms shall be governed by and construed in accordance with the laws of
                    the jurisdiction in which Debate Lab operates, without regard to conflict of law
                    principles.
                  </p>
                  <p>
                    Any disputes arising from these Terms or the Service shall be resolved through
                    binding arbitration in accordance with applicable arbitration rules, except
                    where prohibited by law.
                  </p>
                </Prose>
              </section>

              <Divider className="my-12" />

              <section id="changes-to-terms" className="scroll-mt-24">
                <h2 className="text-2xl font-bold tracking-tight text-foreground mb-4">
                  Changes to Terms
                </h2>
                <Prose>
                  <p>
                    We reserve the right to modify these Terms at any time. We will notify users of
                    material changes by posting the updated Terms on this page and updating the
                    &quot;Last updated&quot; date. Your continued use of the Service after changes
                    become effective constitutes acceptance of the revised Terms.
                  </p>
                  <p>We encourage you to review these Terms periodically for any changes.</p>
                </Prose>
              </section>

              <Divider className="my-12" />

              <section id="contact" className="scroll-mt-24">
                <h2 className="text-2xl font-bold tracking-tight text-foreground mb-4">
                  Contact Us
                </h2>
                <Prose>
                  <p>If you have any questions about these Terms of Service, please contact us:</p>
                  <ul>
                    <li>
                      <strong>Email:</strong>{' '}
                      <a href="mailto:legal@debatelab.ai" className="text-primary hover:underline">
                        legal@debatelab.ai
                      </a>
                    </li>
                  </ul>
                </Prose>
              </section>

              <Divider className="my-12" />

              <footer className="text-sm text-muted-foreground">
                <p>
                  See also:{' '}
                  <Link href="/privacy" className="text-primary hover:underline">
                    Privacy Policy
                  </Link>
                </p>
              </footer>
            </article>
          </div>
        </Container>
      </Section>
    </>
  )
}
