// src/components/summary/summary-card.tsx

'use client'

import { cn } from '@/lib/utils'
import { useSummaryStore } from '@/store/summary-store'

interface SummaryCardProps {
  className?: string
}

export function SummaryCard({ className }: SummaryCardProps) {
  const claudeSummary = useSummaryStore((s) => s.claudeSummary)
  const isSummaryLoading = useSummaryStore((s) => s.isSummaryLoading)
  const topic = useSummaryStore((s) => s.topic)

  return (
    <section className={cn('w-full', className)}>
      {/* Section header */}
      <div className="mb-6">
        <div className="flex items-center gap-3 mb-2">
          <div className="flex items-center justify-center w-10 h-10 rounded-full bg-violet-500/10">
            <span className="text-xl">🎭</span>
          </div>
          <h2 className="text-2xl font-bold text-foreground">Claude&apos;s Summary</h2>
        </div>
        <p className="text-muted-foreground">A neutral analysis of the debate by Claude</p>
      </div>

      {/* Summary content */}
      <div
        className={cn(
          'rounded-xl border-2 border-violet-500/20 bg-violet-500/5 p-6',
          'transition-all duration-300'
        )}
      >
        {isSummaryLoading ? (
          <div className="space-y-4 animate-pulse">
            <div className="h-4 bg-muted rounded w-3/4" />
            <div className="h-4 bg-muted rounded w-full" />
            <div className="h-4 bg-muted rounded w-5/6" />
            <div className="h-4 bg-muted rounded w-full" />
            <div className="h-4 bg-muted rounded w-2/3" />
          </div>
        ) : claudeSummary ? (
          <div className="prose prose-neutral dark:prose-invert max-w-none">
            <div className="whitespace-pre-wrap text-foreground/90 leading-relaxed">
              {claudeSummary}
            </div>
          </div>
        ) : (
          <div className="text-center py-8">
            <div className="text-4xl mb-4">📝</div>
            <h3 className="text-lg font-semibold text-foreground mb-2">Summary Not Available</h3>
            <p className="text-muted-foreground text-sm max-w-md mx-auto">
              Claude&apos;s neutral summary of the debate on &ldquo;{topic}&rdquo; is not yet
              available. This feature generates an objective analysis of both sides&apos; arguments.
            </p>
          </div>
        )}
      </div>

      {/* Attribution */}
      {claudeSummary && (
        <div className="mt-4 flex items-center justify-end gap-2 text-sm text-muted-foreground">
          <span>Generated by</span>
          <span className="font-medium text-violet-600 dark:text-violet-400">
            Claude (Anthropic)
          </span>
        </div>
      )}
    </section>
  )
}
